[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=9dcd40e1-5fe1-46b6-a70d-98c8ccec5a07
Description=我录制的脚本7
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========
MoveTo 705, 379
Delay 1298
KeyDown "Win", 1
Delay 357
KeyDown "2", 1
Delay 251
KeyUp "Win", 1
Delay 6
KeyUp "2", 1
Delay 2000
KeyPress "F6", 1
Delay 1000
KeyDown "Ctrl", 1
Delay 100
KeyDown "V", 1
Delay 100
KeyUp "Ctrl", 1
Delay 100
KeyUp "V", 1
Delay 500
KeyPress "Enter", 1
Delay 5000

KeyPress "Shift", 1
Delay 200
MoveTo 949, 285
Delay 606
LeftDown 1
Delay 7
LeftClick 1
Delay 3
LeftUp 1
Delay 150

KeyPress "c", 1
Delay 20
KeyPress "h", 1
Delay 20
KeyPress "1", 1
Delay 20
KeyPress "0", 1
Delay 20
KeyPress "7", 1
Delay 20
KeyPress "6", 1
Delay 20
KeyPress "2", 1
Delay 20
KeyPress "4", 1
Delay 20
KeyPress "7", 1
Delay 20
KeyPress "9", 1
Delay 20
KeyPress "7", 1
Delay 20
KeyPress "5", 1
Delay 20

Delay 100
MoveTo 956, 333
Delay 713
LeftDown 1
Delay 8
LeftClick 1
Delay 3
LeftUp 1
Delay 150

KeyPress "CapsLock", 1
Delay 150

KeyPress "C", 1
Delay 20
KeyPress "H", 1
Delay 20
KeyPress "E", 1
Delay 20
KeyPress "N", 1
Delay 20
KeyPress "9", 1
Delay 20
KeyPress "4", 1
Delay 20
KeyPress "0", 1
Delay 20
KeyPress "8", 1
Delay 20
KeyPress "1", 1
Delay 20
KeyPress "3", 1
Delay 20

Delay 2000
MoveTo 915, 404
Delay 1524
LeftDown 1
Delay 100
MoveTo 936, 404
Delay 152
MoveTo 989, 404
Delay 136
MoveTo 1123, 404
Delay 1932
LeftUp 1
Delay 2
LeftUp 1

KeyPress "Enter", 1
Delay 200
MoveTo 1000, 450
LeftClick 1
