[General]
MacroID=3ed42b3a-86e4-46d7-9b4d-e44ec356a2b5
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
Description=我录制的脚本1
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========
MoveTo 40, 25
Delay 1102
LeftDoubleClick 1
Delay 114
MoveTo 1466, 29
Delay 1991
LeftDown 1
Delay 1
LeftClick 1
Delay 2
LeftUp 1
MoveTo 766, 52
Delay 903
LeftDown 1
Delay 1
LeftClick 1
Delay 1
LeftUp 1
Delay 812
KeyDown "Ctrl", 1
Delay 2
Delay 145
KeyDown "V", 1
Delay 3
Delay 41
KeyUp "Ctrl", 1
Delay 60
KeyUp "V", 1
Delay 1
Delay 790
KeyDown "Enter", 1
Delay 2
Delay 69
KeyUp "Enter", 1
Delay 1
MoveTo 1085, 364
Delay 1721
LeftDown 1
Delay 2
LeftClick 1
Delay 1
LeftUp 1
MoveTo 1086, 363
Delay 993
KeyDown "N", 1
Delay 3
Delay 73
KeyUp "N", 1
Delay 2
Delay 232
KeyDown "B", 1
Delay 2
Delay 72
KeyUp "B", 1
Delay 159
KeyDown "A", 1
Delay 3
Delay 109
KeyUp "A", 1
Delay 369
KeyDown "1", 1
Delay 3
Delay 105
KeyUp "1", 1
Delay 2
Delay 164
KeyDown "2", 1
Delay 2
Delay 105
KeyUp "2", 1
Delay 3
Delay 124
KeyDown "3", 1
Delay 3
Delay 105
KeyUp "3", 1
Delay 3
Delay 343
KeyDown ".", 1
Delay 2
Delay 109
KeyUp ".", 1
Delay 2
Delay 190
KeyDown "3", 1
Delay 3
Delay 105
KeyUp "3", 1
Delay 3
Delay 110
KeyDown "2", 1
Delay 2
Delay 107
KeyUp "2", 1
Delay 3
Delay 92
KeyDown "1", 1
Delay 3
Delay 106
KeyUp "1", 1
Delay 2
Delay 292
KeyDown "C", 1
Delay 3
Delay 66
KeyUp "C", 1
Delay 3
Delay 120
KeyDown "B", 1
Delay 3
Delay 75
KeyUp "B", 1
Delay 2
Delay 66
KeyDown "A", 1
Delay 74
KeyUp "A", 1
Delay 2
MoveTo 1106, 408
Delay 933
LeftDown 1
Delay 2
LeftDown 1
MoveTo 1108, 409
Delay 84
LeftUp 1
MoveTo 1132, 398
Delay 1418
LeftDown 1
Delay 2
LeftClick 1
Delay 2
LeftUp 1
Delay 786
KeyDown "N", 1
Delay 3
Delay 71
KeyUp "N", 1
Delay 151
KeyDown "B", 1
Delay 2
Delay 72
KeyUp "B", 1
Delay 2
Delay 99
KeyDown "A", 1
Delay 3
Delay 109
KeyUp "A", 1
Delay 2
Delay 259
KeyDown "1", 1
Delay 2
Delay 112
KeyUp "1", 1
Delay 87
KeyDown "2", 1
Delay 3
Delay 104
KeyUp "2", 1
Delay 2
Delay 100
KeyDown "3", 1
Delay 3
Delay 107
KeyUp "3", 1
Delay 3
Delay 417
KeyDown ".", 1
Delay 3
Delay 66
KeyUp ".", 1
Delay 3
Delay 285
KeyDown "3", 1
Delay 3
Delay 110
KeyUp "3", 1
Delay 149
KeyDown "2", 1
Delay 119
KeyUp "2", 1
Delay 105
KeyDown "1", 1
Delay 109
KeyUp "1", 1
Delay 3
Delay 281
KeyDown "C", 1
Delay 2
Delay 69
KeyUp "C", 1
Delay 2
Delay 97
KeyDown "B", 1
Delay 3
Delay 71
KeyUp "B", 1
Delay 103
KeyDown "A", 1
Delay 109
KeyUp "A", 1
Delay 2
MoveTo 1037, 473
Delay 1215
LeftDown 1
Delay 3
LeftDown 1
MoveTo 1250, 481
Delay 2379
LeftUp 1
MoveTo 1231, 505
Delay 964
LeftClick 1
Delay 1
LeftUp 1
'==========以上是按键精灵录制的内容==========
