[General]
MacroID=86e2f04e-91d0-44ee-96dd-9ee8790e7e65
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
Description=我录制的脚本2
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========
MoveTo 24, 43
Delay 745
LeftDoubleClick 1
Delay 111
MoveTo 1476, 17
Delay 1916
LeftDown 1
Delay 2
LeftClick 1
Delay 2
LeftUp 1
MoveTo 786, 57
Delay 702
LeftClick 1
Delay 1
LeftUp 1
MoveTo 773, 43
Delay 1078
KeyDown "Ctrl", 1
Delay 3
Delay 112
KeyDown "V", 1
Delay 4
Delay 68
KeyUp "Ctrl", 1
Delay 1
Delay 35
KeyUp "V", 1
Delay 2
Delay 844
KeyDown "Enter", 1
Delay 1
Delay 67
KeyUp "Enter", 1
Delay 1
MoveTo 1046, 363
Delay 1601
LeftClick 1
Delay 1
LeftUp 1
MoveTo 1048, 363
Delay 1011
KeyDown "N", 1
Delay 2
Delay 71
KeyUp "N", 1
Delay 2
Delay 133
KeyDown "B", 1
Delay 3
Delay 71
KeyUp "B", 1
Delay 3
Delay 799
KeyDown "A", 1
Delay 3
Delay 139
KeyUp "A", 1
Delay 3
Delay 244
KeyDown "1", 1
Delay 2
Delay 141
KeyUp "1", 1
Delay 2
Delay 66
KeyDown "2", 1
Delay 3
Delay 110
KeyUp "2", 1
Delay 2
Delay 156
KeyDown "3", 1
Delay 3
Delay 108
KeyUp "3", 1
Delay 3
Delay 487
KeyDown ".", 1
Delay 2
Delay 61
KeyUp ".", 1
Delay 3
Delay 302
KeyDown "3", 1
Delay 2
Delay 108
KeyUp "3", 1
Delay 3
Delay 201
KeyDown "2", 1
Delay 3
Delay 108
KeyUp "2", 1
Delay 2
Delay 99
KeyDown "1", 1
Delay 3
Delay 112
KeyUp "1", 1
Delay 254
KeyDown "C", 1
Delay 105
KeyUp "C", 1
Delay 67
KeyDown "B", 1
Delay 2
Delay 77
KeyUp "B", 1
Delay 2
Delay 112
KeyDown "A", 1
Delay 3
Delay 107
KeyUp "A", 1
Delay 2
MoveTo 1095, 400
Delay 1094
LeftDown 1
Delay 2
LeftDown 1
MoveTo 1096, 400
Delay 83
LeftUp 1
Delay 1
LeftUp 1
MoveTo 1084, 404
Delay 1529
LeftDown 1
Delay 1
LeftClick 1
Delay 2
LeftUp 1
MoveTo 1079, 402
Delay 772
KeyDown "N", 1
Delay 3
Delay 69
KeyUp "N", 1
Delay 143
KeyDown "B", 1
Delay 3
Delay 66
KeyUp "B", 1
Delay 1
Delay 140
KeyDown "A", 1
Delay 2
Delay 108
KeyUp "A", 1
Delay 493
KeyDown "1", 1
Delay 3
Delay 108
KeyUp "1", 1
Delay 3
Delay 106
KeyDown "2", 1
Delay 2
Delay 114
KeyUp "2", 1
Delay 109
KeyDown "3", 1
Delay 102
KeyUp "3", 1
Delay 420
KeyDown ".", 1
Delay 3
Delay 68
KeyUp ".", 1
Delay 3
Delay 234
KeyDown "3", 1
Delay 3
Delay 107
KeyUp "3", 1
Delay 3
Delay 129
KeyDown "2", 1
Delay 3
Delay 103
KeyUp "2", 1
Delay 3
Delay 98
KeyDown "1", 1
Delay 3
Delay 103
KeyUp "1", 1
Delay 3
Delay 265
KeyDown "C", 1
Delay 3
Delay 71
KeyUp "C", 1
Delay 2
Delay 90
KeyDown "B", 1
Delay 1
Delay 59
KeyUp "B", 1
Delay 2
Delay 81
KeyDown "A", 1
Delay 3
Delay 69
KeyUp "A", 1
Delay 3
MoveTo 1039, 466
Delay 1222
LeftDown 1
Delay 2
LeftDown 1
MoveTo 1258, 467
Delay 1621
LeftUp 1
MoveTo 1215, 506
Delay 1057
LeftDown 1
Delay 3
LeftClick 1
Delay 1
LeftUp 1
'==========以上是按键精灵录制的内容==========
